plp_ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'plp_ecommerce'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('product_details/<int:pk>/', views.product_details, name= 'product_details'),
    path('product_list/', views.product_list,name = 'product_list' ),
    path('customer_details/<int:pk>/', views.customer_details, name='customer_details'),
    path('customer_list/', views.customer_list, name='customer_list'),

]

workingTop/urls.py
from django.contrib import admin
from django.urls import include, path
#include should be in the urls.py created in the app folder

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plp_ecommerce.urls')),
]

plp_ecommerce/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    description = models.TextField(max_length=20, blank=False, null=False)
    price = models.CharField(max_length=10, blank=False, null=False)
    image = models.ImageField(upload_to='product_details/')
    availability = models.BooleanField(default=True)
    #DecimalField(max_decimal)

    def __str__(self):
        return self.name
    
class Customer(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phoneNumber = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=20, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return print(f"Hello {self.firstName} {self.lastName} {self.email}")

plp_ecommerce/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from .models import Product
from .models import Customer

# Create your views here.
def home(request):
    return render(request, 'plp_ecommerce/home.html')

def product_list(request):
    products = Product.objects.all()
    context = {"products": products}
    return render(request, 'plp_ecommerce/product_list.html', context)

def product_details(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {"product": product}
    return render(request, 'plp_ecommerce/product_details.html', context)

def customer_list(request):
    customers = Customer.objects.all()
    context = {'customers':customers}
    return render(request, "plp_ecommerce/customer_list.html", context)

def customer_details(request,pk):
    customer = get_object_or_404(Customer, pk=pk)
    context = {"customer": customer}
    return render(request, "plp_ecommerce/customer_details.html", context)

plp_ecommerce/templates/plp_ecommerce/customer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer details</title>
</head>
<body>
    <h1>Customer details page</h1>
</body>
</html>

plp_ecommerce/templates/plp_ecommerce/customer_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer list</title>
</head>
<body>
    <h1>Customer list page</h1>
    <ul>
        {%for customer in customers%}
        {%endfor%}
     </ul>
</body>
</html>

plp_ecommerce/templates/plp_ecommerce/home.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'plp_ecommerce/styles.css' %}">
    <title>Ecommerce</title>
</head>
<body>
    <h1>Ecommerce home page</h1>
    <nav>
        <ul>
          <li><a href="{% url 'plp_ecommerce:product_list' %}">Products</a></li>
          <li><a href="{% url 'plp_ecommerce:customer_list' %}">Customers</a></li>
        </ul>
    </nav>
</body>
</html>

plp_ecommerce/templates/plp_ecommerce/product_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product details</title>
</head>
<body>
    <h1>Product details page</h1>
</body>
</html>

plp_ecommerce/templates/plp_ecommerce/product_list.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'plp_ecommerce/styles.css' %}">
    <title>Product list</title>
</head>
<body>
    <h1>This is the product list</h1>
    <p>Heyyy</p>
    <ul>
       {% for product in products %} 
       <li>
        <h2>{{product.name}} </h2>
        <p>  {{ product.description}}</p>
        <p> Price: Kshs. {{product.price}}</p>
        <!-- <img src="{{product.image.url}}" alt="{{product.name}}"> -->
        <p> Available: {{product.availability|yesno:"Yes,No"}} </p>
       </li>
       {% endfor %}
    </ul>
</body>
</html>